// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06.Models;

namespace Mission06.Migrations
{
    [DbContext(typeof(MovieDatabaseContext))]
    [Migration("20230213215841_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06.Models.MoviesModel", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            category = "Action/Adventure",
                            director = "Pete Docter",
                            edit = false,
                            lent = "Prof Hilton",
                            notes = "Section 3 is the Best!",
                            rating = "PG",
                            title = "UP",
                            year = 2009
                        },
                        new
                        {
                            ApplicationID = 2,
                            category = "Horrer/Suspense",
                            director = "John Krasinski",
                            edit = false,
                            rating = "PG-13",
                            title = "A Quiet Place",
                            year = 2018
                        },
                        new
                        {
                            ApplicationID = 3,
                            category = "Comedy",
                            director = "Daniel Kwan",
                            edit = true,
                            rating = "R",
                            title = "Everything Everywhere All at Once",
                            year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
