// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06.Models;

namespace Mission06.Migrations
{
    [DbContext(typeof(MovieDatabaseContext))]
    partial class MovieDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            categoryname = "Action/Adventure"
                        },
                        new
                        {
                            categoryID = 2,
                            categoryname = "Comedy"
                        },
                        new
                        {
                            categoryID = 3,
                            categoryname = "Drama"
                        },
                        new
                        {
                            categoryID = 4,
                            categoryname = "Family"
                        },
                        new
                        {
                            categoryID = 5,
                            categoryname = "Horror/Suspense"
                        },
                        new
                        {
                            categoryID = 6,
                            categoryname = "Miscellaneous"
                        },
                        new
                        {
                            categoryID = 7,
                            categoryname = "Television"
                        },
                        new
                        {
                            categoryID = 8,
                            categoryname = "VHS"
                        });
                });

            modelBuilder.Entity("Mission06.Models.MoviesModel", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationID");

                    b.HasIndex("categoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            categoryID = 4,
                            director = "Pete Docter",
                            edit = false,
                            lent = "Prof Hilton",
                            notes = "Section 3 is the Best!",
                            rating = "PG",
                            title = "UP",
                            year = 2009
                        },
                        new
                        {
                            ApplicationID = 2,
                            categoryID = 5,
                            director = "John Krasinski",
                            edit = false,
                            rating = "PG-13",
                            title = "A Quiet Place",
                            year = 2018
                        },
                        new
                        {
                            ApplicationID = 3,
                            categoryID = 1,
                            director = "Daniel Kwan",
                            edit = true,
                            rating = "R",
                            title = "Everything Everywhere All at Once",
                            year = 2022
                        });
                });

            modelBuilder.Entity("Mission06.Models.MoviesModel", b =>
                {
                    b.HasOne("Mission06.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
